meter_data_zip_path: "inputs/halfhourly_dataset.zip"
meter_data_folder_path: "inputs/halfhourly_dataset/"
household_data_file_path: "inputs/household_info.csv"
meter_data_merged_file_path: "outputs/data/electricity_data.csv"
inertia_plot_folder_path: "outputs/figures/inertia/"
cluster_plot_folder_path: "outputs/figures/clusters/"
plot_suffix: ".png"
random_state: 0
